name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.2.0'

      - name: Install dependencies
        run: yarn install

      - name: Generate Prisma client
        run: yarn prisma:generate

      - name: Run build command
        run: yarn build

      - name: Run test command
        run: yarn test
